import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import QRCode from "qrcode";

export const generateTicketPDF = async (ticket: any, applicant: any) => {
    const doc = new jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4",
    });

    // Load Fonts (Simulated for client-side without heavy font files)
    // Note: Standard jsPDF fonts don't support Arabic well. 
    // Ideally, we need a custom font. For this MVP, we might use English or basic transliteration
    // OR we rely on the user understanding it's a basic PDF.
    // TO FIXED ARABIC: We would need to add a .ttf font file as base64. 
    // checking if I can use a simpler approach or if I should assume English for the ticket details for now?
    // Let's stick to English labels with Arabic data if possible, or try to add a font.
    // For safety and speed in MVP: I will use English structure with Latin text to avoid garbled Arabic characters
    // unless I inject a font. Injecting a font in this environment is risky without a file.

    // --- Header ---
    doc.setFillColor(63, 81, 181); // Primary Blue
    doc.rect(0, 0, 210, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("Overseas Travels", 105, 15, { align: "center" });
    doc.setFontSize(12);
    doc.text("Professional Accreditation Exam Ticket", 105, 25, { align: "center" });

    // --- Ticket Info Box ---
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);

    // Ticket Number
    doc.text(`Ticket No: ${ticket.ticketNumber}`, 20, 50);
    doc.text(`Date Issued: ${new Date(ticket.createdAt).toLocaleDateString()}`, 140, 50);

    // --- Passenger Details ---
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 55, 190, 55);

    doc.setFontSize(14);
    doc.text("Passenger Details", 20, 65);

    doc.setFontSize(11);
    doc.text(`Name: ${applicant.fullName}`, 20, 75);
    doc.text(`Mobile: ${applicant.phone}`, 20, 82);
    doc.text(`Passport: ${applicant.id.split('-')[0]} (Ref)`, 120, 75); // Using ID segment as ref

    // --- Journey Details ---
    doc.line(20, 90, 190, 90);
    doc.setFontSize(14);
    doc.text("Journey Details", 20, 100);

    autoTable(doc, {
        startY: 105,
        head: [['From', 'To', 'Date', 'Time', 'Company', 'Bus/Seat']],
        body: [[
            ticket.departureLocation,
            ticket.arrivalLocation,
            new Date(ticket.departureDate).toLocaleDateString(),
            new Date(ticket.departureDate).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            ticket.transportCompany,
            `${ticket.busNumber || '-'} / ${ticket.seatNumber || '-'}`
        ]],
        theme: 'grid',
        headStyles: { fillColor: [63, 81, 181] }
    });

    // --- QR Code ---
    try {
        const qrData = JSON.stringify({
            id: ticket.id,
            ticket: ticket.ticketNumber,
            name: applicant.fullName,
            valid: true
        });
        const qrImage = await QRCode.toDataURL(qrData);
        doc.addImage(qrImage, "PNG", 75, 150, 60, 60);
    } catch (err) {
        console.error("QR Error", err);
    }

    // --- Footer ---
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Please arrive 30 minutes before departure.", 105, 230, { align: "center" });
    doc.text("Show this ticket to the bus driver.", 105, 235, { align: "center" });

    doc.setFontSize(8);
    doc.text("Generated by Overseas System", 105, 280, { align: "center" });

    doc.save(`Ticket-${applicant.fullName}.pdf`);
};
